spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/workpilot
spring.datasource.username=postgres
spring.datasource.password=2805

spring jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=10dfuhoifhwefe85HK85wewf3l28RINijr5U8900JKB-ñkjUJNlk
jwt.expiration=1800000